scope: project
activation: always
name: project
content: |-
  Organization, folder and project are container objects that need special treatment and different structural imlementation.
  They order the overall resource description in the cfg file.

  - organization
    - direct properties of organization like orgpolicies, groups, organization_iam_member
    - folder tree
      - folder properties
        - folder_id
        - name
        - folder_iam_member
        - org_policiy_policy connected to the folder
        - Other folder related resource types
      - projects in the folder
        - project properties name, id
        - resources in project
      - subfolders subtree recursion

  import-id should be output depending on the cli options: --add-import-id and --add-import-id-as-comment

  In general a function for each resource type should be adequate because each may have a special provider schema and response json from the list_assets call.
  There should be a compromize between generalization and specialization for each resource type. For example "ignore" functions for each might be implemented by resource registry or list_assets result handling and the entries for that lists might be read from the discovery-config.yaml file so that they do not need to be hardcoded in each resource types function.
id: dd69097d-e98e-4c96-aa3f-baa0a58cface
project: _user
source_format: cursor
created_at: '2026-02-25T20:30:17.175904+00:00'
updated_at: '2026-02-25T20:30:17.175904+00:00'
store_version: '1'
